export const data = [
  {
    "tokenId": null,
    "id": 141,
    "pageOne": 1,
    "rows": 10,
    "page": {
      "displayNum": 0,
      "curPageNum": 0,
    },
    "pageFlag": true,
    "modelId": "202001021411297650112680",
    "modelType": "0",
    "subordinateId": "202001021138104240112426",
    "modelCode": "contactsModel",
    "modelName": "联系人信息",
    "modelOrder": 1,
    "showNameFlag": "Y",
    "showTabFlag": "0",
    "showTabCode": null,
    "modelDetails": [
      {
        "id": 302,
        "modelId": "202001021411297650112680",
        "pageElId": "202001021411297880112683",
        "pageElCode": "contactsPhone",
        "pageElName": "手机号码",
        "pageElType": "03",
        "isNeed": "Y",
        "needTips": "请填写联系人手机号码",
        "isDefaultShow": "Y",
        "defaultValue": null,
        "elOptions": "[]",
        "minValue": null,
        "maxValue": null,
        "startDateRule": null,
        "startTimeRule": null,
        "dateInterval": null,
        "dateIntervalUnit": null,
        "pageOrder": "1",
      },
      {
        "id": 301,
        "modelId": "202001021411297650112680",
        "pageElId": "202001021411297830112682",
        "pageElCode": "contactsName",
        "pageElName": "姓名",
        "pageElType": "03",
        "isNeed": "Y",
        "needTips": "请填写联系人姓名",
        "isDefaultShow": "Y",
        "defaultValue": null,
        "elOptions": "[]",
        "minValue": null,
        "maxValue": null,
        "startDateRule": null,
        "startTimeRule": null,
        "dateInterval": null,
        "dateIntervalUnit": null,
        "pageOrder": "1",
      },
      {
        "id": 300,
        "modelId": "202001021411297650112680",
        "pageElId": "202001021411297700112681",
        "pageElCode": "insureCompany",
        "pageElName": "投保单位",
        "pageElType": "03",
        "isNeed": "Y",
        "needTips": "请填写投保单位名称",
        "isDefaultShow": "Y",
        "defaultValue": null,
        "elOptions": "[]",
        "minValue": null,
        "maxValue": null,
        "startDateRule": null,
        "startTimeRule": null,
        "dateInterval": null,
        "dateIntervalUnit": null,
        "pageOrder": "1",
      },
    ],
    "modelRelations": [],
  },
  {
    "tokenId": null,
    "id": 191,
    "pageOne": 1,
    "rows": 10,
    "page": {
      "displayNum": 0,
      "curPageNum": 0,
    },
    "pageFlag": true,
    "modelId": "202001021411297480112676",
    "modelType": "0",
    "subordinateId": "202001021138104240112426",
    "modelCode": "guaranteeModel",
    "modelName": "保障项目",
    "modelOrder": 2,
    "showNameFlag": "Y",
    "showTabFlag": "0",
    "showTabCode": null,
    "modelDetails": [
      {
        "id": 299,
        "modelId": "202001021411297480112676",
        "pageElId": "202001021411297610112679",
        "pageElCode": "guaranteeItem_04",
        "pageElName": "意外伤害身故",
        "pageElType": "13",
        "isNeed": "Y",
        "needTips": null,
        "isDefaultShow": "Y",
        "defaultValue": null,
        "elOptions": "[{\"name\":\"1类职业\",\"value\":\"01\",\"isDefault\":\"N\",\"order\":1},{\"name\":\"2类职业\",\"value\":\"02\",\"isDefault\":\"N\",\"order\":2},{\"name\":\"3类职业\",\"value\":\"03\",\"isDefault\":\"N\",\"order\":3},{\"name\":\"4类职业\",\"value\":\"04\",\"isDefault\":\"N\",\"order\":4},{\"name\":\"5类职业\",\"value\":\"05\",\"isDefault\":\"N\",\"order\":5}]",
        "minValue": null,
        "maxValue": null,
        "startDateRule": null,
        "startTimeRule": null,
        "dateInterval": null,
        "dateIntervalUnit": null,
        "pageOrder": "1",
      },
      {
        "id": 298,
        "modelId": "202001021411297480112676",
        "pageElId": "202001021411297570112678",
        "pageElCode": "guaranteeItem_03",
        "pageElName": "团体意外住院津贴",
        "pageElType": "13",
        "isNeed": "Y",
        "needTips": null,
        "isDefaultShow": "Y",
        "defaultValue": null,
        "elOptions": "[{\"name\":\"1类职业\",\"value\":\"01\",\"isDefault\":\"N\",\"order\":1},{\"name\":\"2类职业\",\"value\":\"02\",\"isDefault\":\"N\",\"order\":2},{\"name\":\"3类职业\",\"value\":\"03\",\"isDefault\":\"N\",\"order\":3},{\"name\":\"4类职业\",\"value\":\"04\",\"isDefault\":\"N\",\"order\":4},{\"name\":\"5类职业\",\"value\":\"05\",\"isDefault\":\"N\",\"order\":5}]",
        "minValue": null,
        "maxValue": null,
        "startDateRule": null,
        "startTimeRule": null,
        "dateInterval": null,
        "dateIntervalUnit": null,
        "pageOrder": "1",
      },
      {
        "id": 297,
        "modelId": "202001021411297480112676",
        "pageElId": "202001021411297540112677",
        "pageElCode": "guaranteeItem_02",
        "pageElName": "团体意外伤害医疗",
        "pageElType": "13",
        "isNeed": "Y",
        "needTips": null,
        "isDefaultShow": "Y",
        "defaultValue": null,
        "elOptions": "[{\"name\":\"1类职业\",\"value\":\"01\",\"isDefault\":\"N\",\"order\":1},{\"name\":\"2类职业\",\"value\":\"02\",\"isDefault\":\"N\",\"order\":2},{\"name\":\"3类职业\",\"value\":\"03\",\"isDefault\":\"N\",\"order\":3},{\"name\":\"4类职业\",\"value\":\"04\",\"isDefault\":\"N\",\"order\":4},{\"name\":\"5类职业\",\"value\":\"05\",\"isDefault\":\"N\",\"order\":5}]",
        "minValue": null,
        "maxValue": null,
        "startDateRule": null,
        "startTimeRule": null,
        "dateInterval": null,
        "dateIntervalUnit": null,
        "pageOrder": "1",
      },
    ],
    "modelRelations": [],
  },
  {
    "tokenId": null,
    "id": 192,
    "pageOne": 1,
    "rows": 10,
    "page": {
      "displayNum": 0,
      "curPageNum": 0,
    },
    "pageFlag": true,
    "modelId": "202001021411297920112684",
    "modelType": "0",
    "subordinateId": "202001021138104240112426",
    "modelCode": "insuredTypeModel",
    "modelName": "被保人类型",
    "modelOrder": 3,
    "showNameFlag": "Y",
    "showTabFlag": "0",
    "showTabCode": null,
    "modelDetails": [
      {
        "id": 304,
        "modelId": "202001021411297920112684",
        "pageElId": "202001021411298030112686",
        "pageElCode": "occupation",
        "pageElName": "职业",
        "pageElType": "01",
        "isNeed": "Y",
        "needTips": "请选择职业",
        "isDefaultShow": "Y",
        "defaultValue": null,
        "elOptions": "[{\"name\":\"1类职业\",\"value\":\"01\",\"isDefault\":\"N\",\"order\":1},{\"name\":\"2类职业\",\"value\":\"02\",\"isDefault\":\"N\",\"order\":2},{\"name\":\"3类职业\",\"value\":\"03\",\"isDefault\":\"N\",\"order\":3},{\"name\":\"4类职业\",\"value\":\"04\",\"isDefault\":\"N\",\"order\":4},{\"name\":\"5类职业\",\"value\":\"05\",\"isDefault\":\"N\",\"order\":5}]",
        "minValue": null,
        "maxValue": null,
        "startDateRule": null,
        "startTimeRule": null,
        "dateInterval": null,
        "dateIntervalUnit": null,
        "pageOrder": "2",
      },
      {
        "id": 303,
        "modelId": "202001021411297920112684",
        "pageElId": "202001021411297980112685",
        "pageElCode": "insuredNumber",
        "pageElName": "被保人数",
        "pageElType": "10",
        "isNeed": "Y",
        "needTips": null,
        "isDefaultShow": "Y",
        "defaultValue": null,
        "elOptions": "[]",
        "minValue": 1,
        "maxValue": 20,
        "startDateRule": null,
        "startTimeRule": null,
        "dateInterval": null,
        "dateIntervalUnit": null,
        "pageOrder": "1",
      },
    ],
    "modelRelations": [],
  },
]